site_name: 'KG-Hub Downloader'
repo_name: 'monarch-initiative/kghub-downloader'
repo_url: 'https://github.com/monarch-initiative/kghub-downloader'


nav: 
  - Home: 'index.md'


theme:
    name: 'material'
    docs_dir: docs/
    logo: 'images/monarch-initiative.png'
    favicon: 'images/favicon.ico'
    features:
        - navigation.expand
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
    palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    font:
        text: 'Source Sans Pro'
        code: 'Source Sans Pro Mono'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
          - https://docs.python.org/3/objects.inv
          - https://mkdocstrings.github.io/objects.inv
          - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: True
            merge_init_into_class: True
            separate_signature: True
            heading_level: 3
            show_source: False
            show_root_full_path: False
            show_root_toc_entry: False


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true


extra:
  social:
    - icon: 'fontawesome/solid/house'
      link: 'https://monarchinitiative.org'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/monarch-initiative/'

